[package]
name = "brickadia-gen-v4"
version = "0.1.0"
edition = "2024"

[dependencies]
brickadia = "0.1"
strum = "0.27"
strum_macros = "0.27"
image = "0.25"
imageproc = "0.25"
num-traits = "0.2"
rand = "0.9"
rayon = "1.8"
indicatif = { version = "0.17", features = ["rayon"] }